### ISSUE TITLE
Add support for multi module/project built applications

### ISSUE THREAD

**Issue by malston** [spring-cloud/spring-cloud-pipelines#109]
When a project is comprised of multiple Maven modules or Gradle subprojects, then I want a way to tell sc-pipelines which artifact of these is the deployable. I've already configured github-analytics as a multi subproject Gradle build [here](https://github.com/malston/github-analytics-multi). I plan to do the same for github-webhook. Currently, when `./gradlew artifactId -q | tail -1` is called from the root of the project it returns the artifactId of the last subproject in the list. However, if I explicitly call `./gradlew :api:artifactId` or `./gradlew -p api artifactId` then I get the result I expect. So this may just be as simple as passing in another parameter to `retrieveAppName` function with an optional subproject/module name.

**Comment by marcingrzejszczak** [comment]
Let's take an example of 3 repos. 

- `multi-projects` that has 2 separate fat jars (yes, the 12th factor app is broken with such an approach)
- `multi-module` that has 1 deployable but multiple modules
- `a-very-stupid-name` that has 1 deployable with a single project

In Jenkins we would have the following seed job

```groovy
// a single seed job (generates other jobs)
REPOS = 'http://github.com/foo/multi-projects.git$foo,http://github.com/foo/multi-projects.git$bar,http://github.com/foo/multi-module.git$baz,http://github.com/foo/a-very-stupid-name.git$greeting'
```
The value after `$` is the name of the project. We will also treat it as a potential folder to which we should `cd` to produce the binary. In this case, it will be `foo` and `bar` folders under `multi-projects` repo.  

We will then assert if the folder called e.g. `foo` exists in the repo and if that's the case we will set the `ROOT_PROJECT_DIR` to that value. In Concourse we would just set the env var `ROOT_PROJECT_DIR` directly.  

If there's no such folder then we assume that the root folder is `.`, the root folder.

## SINGLE REPO

_A single pipeline for a repo_

E.g. `a-very-stupid-name.git$greeting` If `$...` is passed for Jenkins then it won't matter cause there will be no matching folder and the `ROOT_PROJECT_DIR` will be `.` The name of the pipeline will be `greeting`.

The location of the pipeline descriptor: `/sc-pipelines.yml` 
The location of the deployable: `/target`

### Pseudo code

```bash
# build everything
PROJECT_ROOT="."
cd ${PROJECT_ROOT} 
./mvnw clean install
# upload only the artifact from my specific module
 ./mvnw clean deploy
# deploy
useScPipelinesFromRootFolder
```

## MULTI-MODULE

_A single pipeline for a repo_

E.g. `multi-module.git$baz`, the `$...` passed for Jenkins **must not** match any modules. If it does then it will be treated as a folder that contains an application, not the module itself. The name of the pipeline will be `baz`.

_TODO: consider being less strict and check if `sc-pipelines.yml` is there in root. If it's there then it means that it's a multi-module project_

In the `sc-pipelines.yml` you can provide the coordinates of the module that will produce the JAR.

```yml
build:
	coordinates: impl:core:foo:bar
	# force that the coordinates are the same as folders
	# impl/core/foo/bar
```

The location of the pipeline descriptor: `/sc-pipelines.yml` 
The location of the deployable: `impl/core/foo/bar/target`

### Pseudo code

```bash
# build everything
# retrieve group id from the root module `/pom.xml`
# retrieve artifact id from the child module `impl/core/foo/bar/pom.xml`
PROJECT_ROOT="."
cd ${PROJECT_ROOT} 
./mvnw clean install
# upload only the artifact from my specific module
moduleCoordinate="impl:core:foo:bar" #parsed from sc-pipelines
./mvnw clean deploy -pl ${moduleCoordinate}
# deploy
useScPipelinesFromRootFolder
```

## MULTI-PROJECT

_One pipeline for each sub project (in case we can reuse credentials we will have 1 seed job)
 otherwise - separate seed jobs_

E.g. `multi-projects.git$foo` and `multi-projects.git$bar`. sc-pipelines will check if there's a folder `foo` for `foo` pipeline and `bar` for `bar` pipeline. Each subproject must have its own maven / gradle wrappers and pipeline descriptor. `ROOT_PROJECT_DIR` will be set to `foo` and `bar` respectively. That means that the project will `cd` to `ROOT_PROJECT_DIR` before executing any code.

### Pseudo code

_foo pipeline_
```bash
# build everything
PROJECT_ROOT="foo"
cd ${PROJECT_ROOT}
./mvnw clean install
# upload only the artifact from my specific module
./mvnw clean deploy
# deploy
useScPipelinesFromRootFolder
```

_bar pipeline_
```bash
# build everything
PROJECT_ROOT="bar"
cd ${PROJECT_ROOT}
./mvnw clean install
# upload only the artifact from my specific module
./mvnw clean deploy
# deploy
useScPipelinesFromRootFolder
```

**Comment by malston** [comment]
Looks like you've put a lot of thought into this... I don't see any issues with this approach. 👍
