### ISSUE TITLE
[enhancement] Use plain containers for each task

### ISSUE THREAD

**Issue by ddieruf** [spring-cloud/spring-cloud-pipelines#143]
Currently, each task in the concourse pipeline has a specific docker image associated ( springcloud/pipeline-base). This image has certain preloaded dependencies.

Instead, use a plain image like ubuntu#16.04 for every task and within the given task initialize the needed dependency(s). For example, in the task of pushing an app to cf, before the work starts do something like:

`apt-get update`
`apt-get install cf-cli`
`...`

I believe this will enhance the portability of the pipeline(s) and remove the dependency/management of the springcloud/pipeline-base image.

**Comment by oiavorskyi** [comment]
Please keep in mind that by doing so we will make the implementation of air-gapped pipelines harder. I assume that a lot of organizations would prefer the possibility of having full control over the dependencies installed as a part of their CI/CD pipelines. Thus it would be easier for them to veto one image or even put it into an internal repository rather than verifying each `apt-get` command change.

**Comment by marcingrzejszczak** [comment]
IMO you can set another base image and instead of sourcing the sc-pipeline's `pipeline.sh` script from Concourse subdir, you can source your custom one, that afterwards sources the `pipeline.sh`. That way you can install whatever you want and control the process.
