### ISSUE TITLE
Summarize the gaps and challenges with Concourse pipeline

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-pipelines#29]
As a Spring user, I'd like to understand the current gaps and challenges leveraging the concourse pipeline for PCF deployments. 

**Acceptance:**
- It would be ideal for me to review the list of pros/cons
- I'd also be interested in any known gaps and workarounds to make a spring-cloud project work seamlessly
- Any other general concerns and/or feature requirements that we need to bring it up with the Concourse team

**Comment by marcingrzejszczak** [comment]
I would prefer not to write about pros and cons cause I'm really biased (I prefer to code my projects instead of configure them via YML) so let's focus on the gaps & workarounds ;)

## GAPS & WORKAROUNDS

- `.m2` is not cached. Each time you have to download the whole internet. Of course the same relates to Gradle. 
  * create a docker image with `.m2` and pass around env variables to change the maven local / copy the maven local from Docker image to `~/.m2` for the current build. Of course this doesn't scale and is a hack, not a proper solution.
- - No artifacts are able to be stored after the build. I understand that the idea of Concourse is to be stateless but for example JUnit results are not parsable - you can't see why a build was broken
  * I'm actually dumping all `surefire-reports` files to the output of a job. It's awful but at least you can then see why a build was broken
- you can't pass parameters between jobs
  * e.g. the pipeline version needs to be pushed as a file on a branch (e.g. https://github.com/marcingrzejszczak/github-webhook/blob/version/version) . That's the trick that @making taught me ;)
  * I had to merge 2 steps into a single step cause I can't pass any params (here in one step I deployed the apps to CF and wanted to pass the properties with the URLs of the apps to the next step)
- The UI in the docker-compose is buggy (sometimes you can't even see any output) - that's why I ended up with using the `fly` CLI only.

**Comment by sabbyanandan** [comment]
Great! This summary is good to start the conversation. I will close this for now.
